version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.24.0
  - dependency-name: ytpl
    versions:
    - 2.1.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
